### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by RickyVaughn2** [masvarn/node-red-contrib-scp#1]
Thank you for creating this :)

When trying to download, node-red crashes.  The error seems to be at line 112 in index.js:  "er is not defined".

**Comment by RickyVaughn2** [comment]
Also, I did change msg.user to msg.username after receiving "Error: Invalid username".

**Comment by Christian-Me** [comment]
Thank you too, This node came handy to download my letsencrypt keys from my router.
same here ... it worked once but after 2nd deploy it crashes even after restart:

```
10 Aug 00:41:59 - [red] Uncaught Exception:
10 Aug 00:41:59 - ReferenceError: er is not defined
    at Client.<anonymous> (C:\Users\cmeinert\.node-red\node_modules\node-red-contrib-scp\index.js:112:7)
    at Client.emit (events.js:311:20)
    at Socket.<anonymous> (C:\Users\cmeinert\.node-red\node_modules\ssh2\lib\client.js:312:10)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
(I had the same user / username issue too - but after changing this it worked - but only once)

**Comment by Christian-Me** [comment]
`let err="..."` helped a bit but the server response seams to be a string (perhaps this depends on the server version). So strict comparison don`t work:

![image](https://user-images.githubusercontent.com/15779507/89743628-314fe500-daa5-11ea-9976-c16ffc19dcbb.png)

```
104:				if (filesize == datasize) {
```

works in my case (ubnt edgeMax router)

**Comment by masvarn** [comment]
I updated the node and I hope that resolved the issue.
